export const employmentDataFields = [
	{
		id: 1,
		institution_name: 'employment_data.employment_institution_1',
		institution_name_label: 'Institution',
		institution_type: 'employment_data.employment_institution_type_1',
		institution_type_label: 'Institution Type',
		employer_type: 'employment_data.employment_employer_type_1',
		employer_type_label: 'Employer Type',
		position: 'employment_data.employment_position_1',
		position_label: 'Position',
		region: 'employment_data.employment_region_1',
		region_label: 'Region',
		country: 'employment_data.employment_country_1',
		country_label: 'Country',
		start_date: 'employment_data.employment_start_date_1',
		start_date_label: 'Start Date',
		end_date: 'employment_data.employment_end_date_1',
		end_date_label: 'End Date',
	},
	{
		id: 2,
		institution_name: 'employment_data.employment_institution_2',
		institution_name_label: 'Institution',
		institution_type: 'employment_data.employment_institution_type_2',
		institution_type_label: 'Institution Type',
		employer_type: 'employment_data.employment_employer_type_2',
		employer_type_label: 'Employer Type',
		position: 'employment_data.employment_position_2',
		position_label: 'Position',
		region: 'employment_data.employment_region_2',
		region_label: 'Region',
		country: 'employment_data.employment_country_2',
		country_label: 'Country',
		start_date: 'employment_data.employment_start_date_2',
		start_date_label: 'Start Date',
		end_date: 'employment_data.employment_end_date_2',
		end_date_label: 'End Date',
	},
	{
		id: 3,
		institution_name: 'employment_data.employment_institution_3',
		institution_name_label: 'Institution',
		institution_type: 'employment_data.employment_institution_type_3',
		institution_type_label: 'Institution Type',
		employer_type: 'employment_data.employment_employer_type_3',
		employer_type_label: 'Employer Type',
		position: 'employment_data.employment_position_3',
		position_label: 'Position',
		region: 'employment_data.employment_region_3',
		region_label: 'Region',
		country: 'employment_data.employment_country_3',
		country_label: 'Country',
		start_date: 'employment_data.employment_start_date_3',
		start_date_label: 'Start Date',
		end_date: 'employment_data.employment_end_date_3',
		end_date_label: 'End Date',
	},
];

export const supportStaffFields = [
	{
		id: 1,
		first_name: 'support_staff.first_name_1',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_1',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_1',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_1',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_1',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_1',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_1',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_1',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_1',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_1',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_1',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_1',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_1',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 2,
		first_name: 'support_staff.first_name_2',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_2',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_2',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_2',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_2',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_2',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_2',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_2',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_2',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_2',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_2',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_2',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_2',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 3,
		first_name: 'support_staff.first_name_3',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_3',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_3',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_3',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_3',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_3',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_3',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_3',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_3',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_3',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_3',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_3',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_3',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 4,
		first_name: 'support_staff.first_name_4',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_4',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_4',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_4',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_4',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_4',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_4',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_4',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_4',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_4',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_4',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_4',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_4',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 5,
		first_name: 'support_staff.first_name_5',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_5',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_5',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_5',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_5',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_5',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_5',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_5',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_5',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_5',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_5',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_5',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_5',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 6,
		first_name: 'support_staff.first_name_6',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_6',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_6',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_6',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_6',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_6',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_6',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_6',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_6',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_6',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_6',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_6',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_6',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 7,
		first_name: 'support_staff.first_name_7',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_7',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_7',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_7',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_7',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_7',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_7',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_7',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_7',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_7',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_7',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_7',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_7',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 8,
		first_name: 'support_staff.first_name_8',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_8',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_8',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_8',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_8',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_8',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_8',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_8',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_8',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_8',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_8',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_8',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_8',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 9,
		first_name: 'support_staff.first_name_9',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_9',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_9',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_9',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_9',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_9',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_9',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_9',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_9',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_9',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_9',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_9',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_9',
		years_of_practice_label: 'Years of Practice',
	},
	{
		id: 10,
		first_name: 'support_staff.first_name_10',
		first_name_label: 'First Name',
		last_name: 'support_staff.last_name_10',
		last_name_label: 'Last Name',
		othernames: 'support_staff.othernames_10',
		othernames_label: 'Othernames',
		dob: 'support_staff.dob_10',
		dob_label: 'Date of Birth',
		phone_number: 'support_staff.phone_number_10',
		phone_number_label: 'Phone Number',
		email: 'support_staff.email_10',
		email_label: 'Email',
		practitioner_type: 'support_staff.practitioner_type_10',
		practitioner_type_label: 'Practitioner Type',
		pt_pin_number: 'support_staff.pt_pin_number_10',
		pt_pin_number_label: 'Pin Number (Pharmacy Tech Only)',
		pt_year_registration: 'support_staff.pt_year_registration_10',
		pt_year_registration_label: 'Year of Registration (Pharmacy Tech Only)',
		mca_education_certificate: 'support_staff.mca_education_certificate_10',
		mca_education_certificate_label:
			'Highest Educational Certificate (MCAs Only)',
		mca_year_obtained: 'support_staff.mca_year_obtained_10',
		mca_year_obtained_label: 'Year Obtained (MCAs Only)',
		mca_certificate_upload: 'support_staff.mca_certificate_upload_10',
		mca_certificate_upload_label: 'Upload Certificate (MCAs Only)',
		years_of_practice: 'support_staff.years_of_practice_10',
		years_of_practice_label: 'Years of Practice',
	},
];

export const epharmacyFormNoticePoints = [
	{
		id: 1,
		point:
			'Only registered retail pharmaceutical entities are eligible to apply.',
	},
	{
		id: 2,
		point:
			'Mandatory registration with the Data Protection Agency and compliance with existing laws, including the Data Protection Act, 2012 (Act 843) is pre-requisite for renewal of the ePharmacy license.',
	},
	{
		id: 3,
		point:
			'The medicines must be registered for use in both the country of origin and the country of destination and use.',
	},
	{
		id: 4,
		point:
			'In situations where the medicine is not registrable in the country of origin, a certificate of pharmaceutical product shall be submitted.',
	},
	{
		id: 5,
		point:
			'Provisions in relation to the prescription and supply of medicines shall be duly complied with.',
	},
	{
		id: 6,
		point:
			'The operator of an online or electronic pharmacy shall keep, in electronic format, all documentations on all transactions and shall make such documentations available for inspection.',
	},
	{
		id: 7,
		point:
			'ePharmacies shall have an obligation to provide periodic reports of ePharmacy transactions undertaken within a specified period as may be determined by the Council.',
	},
];

export const countries = [
	{ name: 'Afghanistan', value: 'AF' },
	{ name: 'land Islands', value: 'AX' },
	{ name: 'Albania', value: 'AL' },
	{ name: 'Algeria', value: 'DZ' },
	{ name: 'American Samoa', value: 'AS' },
	{ name: 'AndorrA', value: 'AD' },
	{ name: 'Angola', value: 'AO' },
	{ name: 'Anguilla', value: 'AI' },
	{ name: 'Antarctica', value: 'AQ' },
	{ name: 'Antigua and Barbuda', value: 'AG' },
	{ name: 'Argentina', value: 'AR' },
	{ name: 'Armenia', value: 'AM' },
	{ name: 'Aruba', value: 'AW' },
	{ name: 'Australia', value: 'AU' },
	{ name: 'Austria', value: 'AT' },
	{ name: 'Azerbaijan', value: 'AZ' },
	{ name: 'Bahamas', value: 'BS' },
	{ name: 'Bahrain', value: 'BH' },
	{ name: 'Bangladesh', value: 'BD' },
	{ name: 'Barbados', value: 'BB' },
	{ name: 'Belarus', value: 'BY' },
	{ name: 'Belgium', value: 'BE' },
	{ name: 'Belize', value: 'BZ' },
	{ name: 'Benin', value: 'BJ' },
	{ name: 'Bermuda', value: 'BM' },
	{ name: 'Bhutan', value: 'BT' },
	{ name: 'Bolivia', value: 'BO' },
	{ name: 'Bosnia and Herzegovina', value: 'BA' },
	{ name: 'Botswana', value: 'BW' },
	{ name: 'Bouvet Island', value: 'BV' },
	{ name: 'Brazil', value: 'BR' },
	{ name: 'British Indian Ocean Territory', value: 'IO' },
	{ name: 'Brunei Darussalam', value: 'BN' },
	{ name: 'Bulgaria', value: 'BG' },
	{ name: 'Burkina Faso', value: 'BF' },
	{ name: 'Burundi', value: 'BI' },
	{ name: 'Cambodia', value: 'KH' },
	{ name: 'Cameroon', value: 'CM' },
	{ name: 'Canada', value: 'CA' },
	{ name: 'Cape Verde', value: 'CV' },
	{ name: 'Cayman Islands', value: 'KY' },
	{ name: 'Central African Republic', value: 'CF' },
	{ name: 'Chad', value: 'TD' },
	{ name: 'Chile', value: 'CL' },
	{ name: 'China', value: 'CN' },
	{ name: 'Christmas Island', value: 'CX' },
	{ name: 'Cocos (Keeling) Islands', value: 'CC' },
	{ name: 'Colombia', value: 'CO' },
	{ name: 'Comoros', value: 'KM' },
	{ name: 'Congo', value: 'CG' },
	{ name: 'Congo, The Democratic Republic of the', value: 'CD' },
	{ name: 'Cook Islands', value: 'CK' },
	{ name: 'Costa Rica', value: 'CR' },
	{ name: "Cote D'Ivoire", value: 'CI' },
	{ name: 'Croatia', value: 'HR' },
	{ name: 'Cuba', value: 'CU' },
	{ name: 'Cyprus', value: 'CY' },
	{ name: 'Czech Republic', value: 'CZ' },
	{ name: 'Denmark', value: 'DK' },
	{ name: 'Djibouti', value: 'DJ' },
	{ name: 'Dominica', value: 'DM' },
	{ name: 'Dominican Republic', value: 'DO' },
	{ name: 'Ecuador', value: 'EC' },
	{ name: 'Egypt', value: 'EG' },
	{ name: 'El Salvador', value: 'SV' },
	{ name: 'Equatorial Guinea', value: 'GQ' },
	{ name: 'Eritrea', value: 'ER' },
	{ name: 'Estonia', value: 'EE' },
	{ name: 'Ethiopia', value: 'ET' },
	{ name: 'Falkland Islands (Malvinas)', value: 'FK' },
	{ name: 'Faroe Islands', value: 'FO' },
	{ name: 'Fiji', value: 'FJ' },
	{ name: 'Finland', value: 'FI' },
	{ name: 'France', value: 'FR' },
	{ name: 'French Guiana', value: 'GF' },
	{ name: 'French Polynesia', value: 'PF' },
	{ name: 'French Southern Territories', value: 'TF' },
	{ name: 'Gabon', value: 'GA' },
	{ name: 'Gambia', value: 'GM' },
	{ name: 'Georgia', value: 'GE' },
	{ name: 'Germany', value: 'DE' },
	{ name: 'Ghana', value: 'GH' },
	{ name: 'Gibraltar', value: 'GI' },
	{ name: 'Greece', value: 'GR' },
	{ name: 'Greenland', value: 'GL' },
	{ name: 'Grenada', value: 'GD' },
	{ name: 'Guadeloupe', value: 'GP' },
	{ name: 'Guam', value: 'GU' },
	{ name: 'Guatemala', value: 'GT' },
	{ name: 'Guernsey', value: 'GG' },
	{ name: 'Guinea', value: 'GN' },
	{ name: 'Guinea-Bissau', value: 'GW' },
	{ name: 'Guyana', value: 'GY' },
	{ name: 'Haiti', value: 'HT' },
	{ name: 'Heard Island and Mcdonald Islands', value: 'HM' },
	{ name: 'Holy See (Vatican City State)', value: 'VA' },
	{ name: 'Honduras', value: 'HN' },
	{ name: 'Hong Kong', value: 'HK' },
	{ name: 'Hungary', value: 'HU' },
	{ name: 'Iceland', value: 'IS' },
	{ name: 'India', value: 'IN' },
	{ name: 'Indonesia', value: 'ID' },
	{ name: 'Iran, Islamic Republic Of', value: 'IR' },
	{ name: 'Iraq', value: 'IQ' },
	{ name: 'Ireland', value: 'IE' },
	{ name: 'Isle of Man', value: 'IM' },
	{ name: 'Israel', value: 'IL' },
	{ name: 'Italy', value: 'IT' },
	{ name: 'Jamaica', value: 'JM' },
	{ name: 'Japan', value: 'JP' },
	{ name: 'Jersey', value: 'JE' },
	{ name: 'Jordan', value: 'JO' },
	{ name: 'Kazakhstan', value: 'KZ' },
	{ name: 'Kenya', value: 'KE' },
	{ name: 'Kiribati', value: 'KI' },
	{ name: "Korea, Democratic People's Republic", value: 'KP' },
	{ name: 'Korea, Republic', value: 'KR' },
	{ name: 'Kuwait', value: 'KW' },
	{ name: 'Kyrgyzstan', value: 'KG' },
	{ name: "Lao People'S Democratic Republic", value: 'LA' },
	{ name: 'Latvia', value: 'LV' },
	{ name: 'Lebanon', value: 'LB' },
	{ name: 'Lesotho', value: 'LS' },
	{ name: 'Liberia', value: 'LR' },
	{ name: 'Libyan Arab Jamahiriya', value: 'LY' },
	{ name: 'Liechtenstein', value: 'LI' },
	{ name: 'Lithuania', value: 'LT' },
	{ name: 'Luxembourg', value: 'LU' },
	{ name: 'Macao', value: 'MO' },
	{ name: 'Macedonia, The Former Yugoslav Republic of', value: 'MK' },
	{ name: 'Madagascar', value: 'MG' },
	{ name: 'Malawi', value: 'MW' },
	{ name: 'Malaysia', value: 'MY' },
	{ name: 'Maldives', value: 'MV' },
	{ name: 'Mali', value: 'ML' },
	{ name: 'Malta', value: 'MT' },
	{ name: 'Marshall Islands', value: 'MH' },
	{ name: 'Martinique', value: 'MQ' },
	{ name: 'Mauritania', value: 'MR' },
	{ name: 'Mauritius', value: 'MU' },
	{ name: 'Mayotte', value: 'YT' },
	{ name: 'Mexico', value: 'MX' },
	{ name: 'Micronesia, Federated States of', value: 'FM' },
	{ name: 'Moldova, Republic of', value: 'MD' },
	{ name: 'Monaco', value: 'MC' },
	{ name: 'Mongolia', value: 'MN' },
	{ name: 'Montenegro', value: 'ME' },
	{ name: 'Montserrat', value: 'MS' },
	{ name: 'Morocco', value: 'MA' },
	{ name: 'Mozambique', value: 'MZ' },
	{ name: 'Myanmar', value: 'MM' },
	{ name: 'Namibia', value: 'NA' },
	{ name: 'Nauru', value: 'NR' },
	{ name: 'Nepal', value: 'NP' },
	{ name: 'Netherlands', value: 'NL' },
	{ name: 'Netherlands Antilles', value: 'AN' },
	{ name: 'New Caledonia', value: 'NC' },
	{ name: 'New Zealand', value: 'NZ' },
	{ name: 'Nicaragua', value: 'NI' },
	{ name: 'Niger', value: 'NE' },
	{ name: 'Nigeria', value: 'NG' },
	{ name: 'Niue', value: 'NU' },
	{ name: 'Norfolk Island', value: 'NF' },
	{ name: 'Northern Mariana Islands', value: 'MP' },
	{ name: 'Norway', value: 'NO' },
	{ name: 'Oman', value: 'OM' },
	{ name: 'Pakistan', value: 'PK' },
	{ name: 'Palau', value: 'PW' },
	{ name: 'Palestinian Territory, Occupied', value: 'PS' },
	{ name: 'Panama', value: 'PA' },
	{ name: 'Papua New Guinea', value: 'PG' },
	{ name: 'Paraguay', value: 'PY' },
	{ name: 'Peru', value: 'PE' },
	{ name: 'Philippines', value: 'PH' },
	{ name: 'Pitcairn', value: 'PN' },
	{ name: 'Poland', value: 'PL' },
	{ name: 'Portugal', value: 'PT' },
	{ name: 'Puerto Rico', value: 'PR' },
	{ name: 'Qatar', value: 'QA' },
	{ name: 'Reunion', value: 'RE' },
	{ name: 'Romania', value: 'RO' },
	{ name: 'Russian Federation', value: 'RU' },
	{ name: 'RWANDA', value: 'RW' },
	{ name: 'Saint Helena', value: 'SH' },
	{ name: 'Saint Kitts and Nevis', value: 'KN' },
	{ name: 'Saint Lucia', value: 'LC' },
	{ name: 'Saint Pierre and Miquelon', value: 'PM' },
	{ name: 'Saint Vincent and the Grenadines', value: 'VC' },
	{ name: 'Samoa', value: 'WS' },
	{ name: 'San Marino', value: 'SM' },
	{ name: 'Sao Tome and Principe', value: 'ST' },
	{ name: 'Saudi Arabia', value: 'SA' },
	{ name: 'Senegal', value: 'SN' },
	{ name: 'Serbia', value: 'RS' },
	{ name: 'Seychelles', value: 'SC' },
	{ name: 'Sierra Leone', value: 'SL' },
	{ name: 'Singapore', value: 'SG' },
	{ name: 'Slovakia', value: 'SK' },
	{ name: 'Slovenia', value: 'SI' },
	{ name: 'Solomon Islands', value: 'SB' },
	{ name: 'Somalia', value: 'SO' },
	{ name: 'South Africa', value: 'ZA' },
	{ name: 'South Georgia and the South Sandwich Islands', value: 'GS' },
	{ name: 'Spain', value: 'ES' },
	{ name: 'Sri Lanka', value: 'LK' },
	{ name: 'Sudan', value: 'SD' },
	{ name: 'Suriname', value: 'SR' },
	{ name: 'Svalbard and Jan Mayen', value: 'SJ' },
	{ name: 'Swaziland', value: 'SZ' },
	{ name: 'Sweden', value: 'SE' },
	{ name: 'Switzerland', value: 'CH' },
	{ name: 'Syrian Arab Republic', value: 'SY' },
	{ name: 'Taiwan, Province of China', value: 'TW' },
	{ name: 'Tajikistan', value: 'TJ' },
	{ name: 'Tanzania, United Republic of', value: 'TZ' },
	{ name: 'Thailand', value: 'TH' },
	{ name: 'Timor-Leste', value: 'TL' },
	{ name: 'Togo', value: 'TG' },
	{ name: 'Tokelau', value: 'TK' },
	{ name: 'Tonga', value: 'TO' },
	{ name: 'Trinidad and Tobago', value: 'TT' },
	{ name: 'Tunisia', value: 'TN' },
	{ name: 'Turkey', value: 'TR' },
	{ name: 'Turkmenistan', value: 'TM' },
	{ name: 'Turks and Caicos Islands', value: 'TC' },
	{ name: 'Tuvalu', value: 'TV' },
	{ name: 'Uganda', value: 'UG' },
	{ name: 'Ukraine', value: 'UA' },
	{ name: 'United Arab Emirates', value: 'AE' },
	{ name: 'United Kingdom', value: 'GB' },
	{ name: 'United States', value: 'US' },
	{ name: 'United States Minor Outlying Islands', value: 'UM' },
	{ name: 'Uruguay', value: 'UY' },
	{ name: 'Uzbekistan', value: 'UZ' },
	{ name: 'Vanuatu', value: 'VU' },
	{ name: 'Venezuela', value: 'VE' },
	{ name: 'Viet Nam', value: 'VN' },
	{ name: 'Virgin Islands, British', value: 'VG' },
	{ name: 'Virgin Islands, U.S.', value: 'VI' },
	{ name: 'Wallis and Futuna', value: 'WF' },
	{ name: 'Western Sahara', value: 'EH' },
	{ name: 'Yemen', value: 'YE' },
	{ name: 'Zambia', value: 'ZM' },
	{ name: 'Zimbabwe', value: 'ZW' },
];
